### ISSUE TITLE
StatefulSet using AWS EBS - Test Scaling - Incorrect Data shown 

### ISSUE THREAD

**Issue by reagaros** [aws-containers/eks-app-mesh-polyglot-demo#10]
StatefulSet using AWS EBS - Test Scaling - Incorrect Data shown, this is a cosmetic issue where after scaling the replicas to 3 there is a line which says `You will see 5 servers are running.` Since the replicas are only scaled to 3 not sure how the servers could be 5.

Secondly after this line `It will show the same data that leader has.` it shows the following data that the table might have:
```
+--------+----------+
| prodId | prodName |
+--------+----------+
| 1      | Desk1    |
+--------+----------+
```
All the examples have been talking about the data of `999    | Mountain Bike` and since suddenly we are saying it could have `1      | Desk1 ` the users might be confused.

**Comment by praseedasathaye** [comment]
Fixed both issues
