### ISSUE TITLE
Observability - Logs, Traces and Metric - Xray - Does not fetch any traces

### ISSUE THREAD

**Issue by reagaros** [aws-containers/eks-app-mesh-polyglot-demo#5]
Observability - Logs, Traces and Metric - Xray - chapter where it says to View Traces, does not really fetch any traces. This happens even after the deployed application is accessed. Tried this twice still did not work

**Comment by praseedasathaye** [comment]
We discussed about this when we had meeting. You will be checking if works with old AWS console.

**Comment by praseedasathaye** [comment]
Please check and let me know. We can reopen the issue again.
