### ISSUE TITLE
Autoscaling - HPA - references incorrect namespace "workshop"

### ISSUE THREAD

**Issue by reagaros** [aws-containers/eks-app-mesh-polyglot-demo#6]
Autoscaling - HPA - This chapter has this line : `You can go to Cloudwatch -> Metrics -> All Metrics -> and select the namespace **workshop** and find the metric pod_cpu_utilization_over_pod_limit. You can also click this [cloudwatch metrics ] to see CPU Utilization (Over Limit).` Here the workshop refers to cloudwatch metric namespace and not kubernetes namespace as cloudwtach namespace with name **workshop** is never created. This should refer to the **ContainerInsights** namespace.

**Comment by praseedasathaye** [comment]
Fixed
