### ISSUE TITLE
catalog_deployment.yaml file has an additional . for the mountPath

### ISSUE THREAD

**Issue by reagaros** [aws-containers/eks-app-mesh-polyglot-demo#7]
`catalog_deployment.yaml `file has an additional `.` for  `mountPath: {{ .Values.catalog.volume.path }}.` on line 26. This causes the application to not function correctly as it creates a mount inside the container with value `/product.` The trailing `.` should be removed from `catalog_deployment.yaml`

**Comment by praseedasathaye** [comment]
Fixed
