### ISSUE TITLE
StatefulSet using AWS EBS - Test MySQL - Application Testing - cd command missing

### ISSUE THREAD

**Issue by reagaros** [aws-containers/eks-app-mesh-polyglot-demo#9]
StatefulSet using AWS EBS - Test MySQL - [Application Testing](https://catalog.us-east-1.prod.workshops.aws/v2/workshops/76a5dd80-3249-4101-8726-9be3eeee09b2/en-US/pesistentstorage-ebs/testmysql#application-testing) section has an helm upgrade command `helm upgrade --reuse-values -f ~/environment/eks-app-mesh-polyglot-demo/workshop/helm-chart/values-ebs.yaml workshop workshop/helm-chart/` this refers to the helm chart `workshop/helm-chart/` but does not have instructions to cd to the direct which has the `workshop` folder. Without the `cd` users might not understand why the command is failing.

There should be an addition command such as `cd ~/environment/eks-app-mesh-polyglot-demo`

**Comment by praseedasathaye** [comment]
Fixed
